version: '3.0'

expectations:
  population_size: 1000

actions:

  write_something:
    run: python:latest -c 'import pathlib; pathlib.Path("output/something").touch()'
    outputs:
      highly_sensitive:
        cohort: output/something

  write_something_else:
    run: python:latest -c 'import pathlib; pathlib.Path("output/something_else").touch()'
    needs: [write_something]
    outputs:
      highly_sensitive:
        cohort: output/something_else
